### ISSUE TITLE
When I execute yarn run init in ubuntu, I get an error, and I don't know how to deal with it.

### ISSUE THREAD

**Issue by SiriusXT** [ian13456/mine.js#19]
When I execute ’yarn run init‘ in ubuntu, I get an error, and I don't know how to deal with it.
![图片](https://user-images.githubusercontent.com/37627919/109163133-f2b91800-77b3-11eb-9c8d-82114d3568ac.png)

**Comment by ian13456** [comment]
Remember to make a copy of `.env.sample` and rename it as `.env`.

My bad for not putting it on the README 😅

**Comment by SiriusXT** [comment]
十分感谢，这个问题解决了，
但是遇到了一定新的问题，
![图片](https://user-images.githubusercontent.com/37627919/109165326-63613400-77b6-11eb-86a0-37d66382f385.png)
![图片](https://user-images.githubusercontent.com/37627919/109165430-80960280-77b6-11eb-869b-d4cdceec2739.png)

**Comment by SiriusXT** [comment]
Thank you very much, this problem has been solved, but some new problems have been encountered,
![图片](https://user-images.githubusercontent.com/37627919/109165516-9b687700-77b6-11eb-91ad-3a63606ff0e3.png)
![图片](https://user-images.githubusercontent.com/37627919/109165524-9d323a80-77b6-11eb-9ff1-3ef9d7f6a45b.png)

**Comment by ian13456** [comment]
Can you send me the output for `docker ps`? Seems like you already have something running on port 5432.

**Comment by SiriusXT** [comment]
> 
> 
> Can you send me the output for `docker ps`? Seems like you already have something running on port 5432.

![Uploading 图片.png…]()

**Comment by SiriusXT** [comment]
> 
> 
> Can you send me the output for `docker ps`? Seems like you already have something running on port 5432.

![图片](https://user-images.githubusercontent.com/37627919/109165875-07e37600-77b7-11eb-8232-64b93b89c7c7.png)

**Comment by SiriusXT** [comment]
> 
> 
> > Can you send me the output for `docker ps`? Seems like you already have something running on port 5432.
> 
> ![图片](https://user-images.githubusercontent.com/37627919/109165875-07e37600-77b7-11eb-8232-64b93b89c7c7.png)

当我kill了之后
> 
> 
> 您可以将输出发送给我 `docker ps`吗？ 似乎您已经在端口5432上运行了某些设备。

When i kill postgres之后，
![图片](https://user-images.githubusercontent.com/37627919/109167410-b3d99100-77b8-11eb-8f7a-f48e11130976.png)

**Comment by SiriusXT** [comment]
> 
> 
> Can you send me the output for `docker ps`? Seems like you already have something running on port 5432.

When i kill postgres,
![图片](https://user-images.githubusercontent.com/37627919/109167581-e1263f00-77b8-11eb-8bac-de4c2dfaa198.png)
The docker port does not seem to be mapped

**Comment by ian13456** [comment]
`yarn`, then `yarn run init` seems to work for me. What if you reclone the repo?
