### ISSUE TITLE
Is project will grow again?:)

### ISSUE THREAD

**Issue by Fi1osof** [ian13456/mine.js#2]
Hi! 
Yes, it's starts again? Have new communication channels?

**Comment by ian13456** [comment]
Hopefully... was just going to message you on discord XD

**Comment by ian13456** [comment]
I just setup a new discord server for anyone interested :+1:

**Comment by Fi1osof** [comment]
Cool!

> Hopefully... was just going to message you on discord XD

Link can be readed from raw source. Many people will miss them.

**Comment by ian13456** [comment]
What do you mean?

**Comment by Fi1osof** [comment]
I can find discord link only in readme source
```
![](https://i.imgur.com/B3GoQ4p.png)

<a href="https://discord.gg/Xp5cStm" align="center">
<img src="https://img.shields.io/discord/648532255979077635.svg?style=for-the-badge" />
</a>
```
But now i understood it's imaged link:)
![aba4465227](https://user-images.githubusercontent.com/2550668/69587975-414b9580-0ff8-11ea-802d-117d2fee5237.png)
