### ISSUE TITLE
'RUST_BACKTRACE' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by Alchemist0823** [ian13456/mine.js#31]

**Comment by ian13456** [comment]
I'm guessing you're working on a Windows OS right? This happens because windows have its own way of having environmental variables. Just remove the `RUST_BACKTRACE=1` and run this only instead:
```bash
cargo watch -c -w server -w metadata -x "run --release"
```

**Comment by ian13456** [comment]
Just updated the readme for clearer instructions!

**Comment by Alchemist0823** [comment]
Thanks, amazing work so far
