### ISSUE TITLE
Online demo

### ISSUE THREAD

**Issue by talentlessguy** [ian13456/mine.js#4]

**Comment by ian13456** [comment]
Currently there isn't any online demo. A demo of mc.js, previous version of the project, can be found here: https://minecraft.prisma-cms.com/

**Comment by Fi1osof** [comment]
> Currently there isn't any online demo. A demo of mc.js, previous version of the project, can be found here: https://minecraft.prisma-cms.com/

Before you need signup on mail site: https://prisma-cms.com/

**Comment by ian13456** [comment]
Yup!
